Ignore missing servers or snippets when removing from map
saltstack-formulas/nginx-formula pull request #275
Opened 2021-01-23 14:05 UTC by anderbubble

nginx.servers_config wants a lightened copy of the nginx map
to render as json; but, when it was trying to remove the
servers and snippets keys from the map it assumed their presence,
causing a KeyError if they were not present by its use of .pop().

While wrapping these in an "if" clause would likely be more
correct, along with replacing .pop() with del (if jinja even
supports that) the simplest change here is to just specify a
default value for .pop(), which obviates the KeyError.

Fixes #274
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch issues/274
# Changes to be committed:
#	modified:   nginx/servers_config.sls
#

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

### Describe the changes you're proposing

### Pillar / config required to test the proposed changes

### Debug log showing how the proposed changes work

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

2021-04-13 20:34 UTC, javierbertoli requested changes
@anderbubble good catch.

If possible, mind you do a few more changes that are relevant?

1. Add a similar fix in the [snippets.sls](https://github.com/saltstack-formulas/nginx-formula/blob/master/nginx/snippets.sls#L11-L12) file
2. Delete [this line](https://github.com/saltstack-formulas/nginx-formula/blob/master/test/salt/passenger/pillar/nginx.sls#L5), [this block](https://github.com/saltstack-formulas/nginx-formula/blob/master/test/salt/passenger/pillar/nginx.sls#L24-L27) and [these lines](https://github.com/saltstack-formulas/nginx-formula/blob/master/test/salt/passenger/pillar/nginx.sls#L67-L68) so we have a test for this fix.
3. Amend the commit message to something like `fix(config): ignore missing servers or snippets` so our automated versioning does not complain (check [here](https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst#relationship-between-commit-type-and-version-bump) for more details)

With these other minor changes, we'll have testing in place for the issue and it will be OK to be merged

2021-04-13 20:34 UTC, javierbertoli commented on nginx/servers_config.sls
> +{%- do _nginx.pop('servers', None) %}
Perhaps, following your comments, you can change this to
```jinja
{%- do _nginx.pop('snippets', None) if nginx.snippets is defined %}
{%- do _nginx.pop('servers', None) if nginx.servers is defined %}
```
wdyt?

2021-04-16 11:57 UTC, javierbertoli commented
@anderbubble ping?

2021-04-20 03:30 UTC, anderbubble commented
I'm here; just busy. I expect I can perform the additional changes you suggested; it just might take me a bit to get to it.

2021-04-20 18:42 UTC, javierbertoli commented
@anderbubble wonderful! I'll wait for your changes to merge this.

2021-06-14 15:24 UTC, myii commented
>     1. Add a similar fix in the [snippets.sls](https://github.com/saltstack-formulas/nginx-formula/blob/master/nginx/snippets.sls#L11-L12) file
> 
>     3. Amend the commit message to something like `fix(config): ignore missing servers or snippets` so our automated versioning does not complain (check [here](https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst#relationship-between-commit-type-and-version-bump) for more details)

Updated this PR to complete the above steps requested by @javierbertoli.  Includes resolving this review comment:

* https://github.com/saltstack-formulas/nginx-formula/pull/275#discussion_r612749949

2021-06-14 15:25 UTC, javierbertoli approved these changes

2021-06-14 17:47 UTC, merged

2021-06-14 17:48 UTC, javierbertoli commented
Thanks you @anderbubble & @myii for this!