type(fix): remove service depedency
saltstack-formulas/nginx-formula pull request #277
Opened 2021-03-13 20:55 UTC by toanju

servers_config should run without service dependency. As documented service with config is managed in servers.sls.

2021-03-14 06:31 UTC, myii commented
This would be effectively reverting #177, so it would be good to look at the reason(s) it was included in the first place.

@amontalban @noelmcloughlin Any particulars you can share?

2021-03-14 13:18 UTC, javierbertoli commented
I think https://github.com/saltstack-formulas/nginx-formula/pull/177#issuecomment-384756097 explains why that `require_in` is there. Am I right?

2021-03-14 20:24 UTC, toanju commented
From my understanding `nginx_service_reload` will do a reload hence I don't see the `require_in` for the service required at this stage. Maybe extending the actual required cases in `servers.sls` might be a better solution than having a service dependency in this config only state. From looking at #177 this might be only file: nginx_server_enabled_dir and file: nginx_server_available_dir.

Looking forward to get a better understanding from the feedback of @amontalban / @noelmcloughlin.

2021-03-14 21:52 UTC, noelmcloughlin commented
I merged #177 because it was open for 9 months, but had no other involvement. Two people reviewed #177 and another person reviewed related #176.  If custom configuration files are provided we probably want (a) Nginx service to wait for `require_in` OR (b) Nginx service to restart due to `onchanges_in`.  That is my interpretation of #176 and #177.

2021-03-15 20:40 UTC, toanju commented
K, instead of having a separate `nginx_service_reload` I now extended `nginx_service` in `servers.sls` to have the same behavior as in the original PR. Let me know if this is acceptable.

2021-03-15 21:50 UTC, toanju commented
in some cases nginx was started before some config files were deleted and on gentoo and arch a symlink was created without having the dir available hence added:
* wait for all file states (create and delete)
* create dirs for symlinked files

2021-03-19 10:09 UTC, toanju commented
@myii, @javierbertoli, @amontalban, @noelmcloughlin are there any open questions or can this be merged?

2021-03-22 11:43 UTC, javierbertoli requested changes
@toanju I know you didn't add it, but do you find a reason for [this loop](https://github.com/saltstack-formulas/nginx-formula/blob/144b9bd0c9299f00d44f02550d0e4b03b356fed9/nginx/servers_config.sls#L102-L104)? If not, can you remove it while you're at it?

2021-03-26 20:46 UTC, toanju commented
@javierbertoli, just removed it. Couldn't see a reason either.

2021-03-26 21:27 UTC, myii commented
@sticky-note Will you be reviewing this before merge?
@javierbertoli Or have you already reviewed it?

2021-03-29 11:42 UTC, javierbertoli approved these changes

2021-03-29 11:43 UTC, javierbertoli commented
@myii, @toanju I think we're OK to merge these changes.

2021-03-29 14:16 UTC, merged

2021-03-29 14:17 UTC, myii commented
@toanju Thanks for the PR -- merged.
Appreciate the review, @javierbertoli.

2021-03-29 19:36 UTC, toanju commented
Thanks a lot all!

2021-03-29 19:42 UTC, myii commented
@toanju Would you mind responding to this query?

* https://github.com/saltstack-formulas/nginx-formula/commit/5d7fc8d5ba4828654c41e9f13f128260f8cf2869#r48859525

2021-03-29 19:52 UTC, toanju commented
doen